INSERT INTO USER (USER_ID, EMAIL) VALUES (1, 'tiewkeehui95@hotmail.com');
INSERT INTO USER (USER_ID, EMAIL) VALUES (2, 'david@yahoo.com');
INSERT INTO USER (USER_ID, EMAIL) VALUES (3, 'douglas@gmail.com');

INSERT INTO FEATURE (FEATURE_ID, FEATURE_NAME) VALUES (1, 'CREATE USER');
INSERT INTO FEATURE (FEATURE_ID, FEATURE_NAME) VALUES (2, 'APPROVE TRANSFER');
INSERT INTO FEATURE (FEATURE_ID, FEATURE_NAME) VALUES (3, 'APPROVE LOAN');

INSERT INTO USER_FEATURE (ID, USER_ID, FEATURE_ID) VALUES (1, 1, 1);
INSERT INTO USER_FEATURE (ID, USER_ID, FEATURE_ID) VALUES (2, 1, 2);
INSERT INTO USER_FEATURE (ID, USER_ID, FEATURE_ID) VALUES (3, 1, 3);
INSERT INTO USER_FEATURE (ID, USER_ID, FEATURE_ID) VALUES (4, 2, 2);
INSERT INTO USER_FEATURE (ID, USER_ID, FEATURE_ID) VALUES (5, 3, 3);