DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  USER_ID INT IDENTITY PRIMARY KEY,
  EMAIL VARCHAR(250) NOT NULL,
  UNIQUE KEY EMAIL_UNIQUE (EMAIL)
);

DROP TABLE IF EXISTS FEATURE;

CREATE TABLE FEATURE (
  FEATURE_ID INT IDENTITY PRIMARY KEY,
  FEATURE_NAME VARCHAR(250) NOT NULL,
  UNIQUE KEY FEATURE_NAME_UNIQUE (FEATURE_NAME)
);

DROP TABLE IF EXISTS USER_FEATURE;

CREATE TABLE USER_FEATURE (
  ID INT IDENTITY PRIMARY KEY,
  USER_ID INT,
  FEATURE_ID INT,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
  FOREIGN KEY (FEATURE_ID) REFERENCES FEATURE(FEATURE_ID)
);